### ISSUE TITLE
atscan error

### ISSUE THREAD

**Issue by cacaocaca** [AlisamTechnology/ATSCAN#1]
Hi when i do example perl atscan.pl --dork inurl:".php?cat="intext:"Buy Now"  --level 100 --exp --%27 --valid SQL  i reciever this error 
[!] [5:26:48] [24/106]
[!] TARGET: http://hackingforum.ru/showthread.php?tid=23273
Use of uninitialized value in subroutine entry at atscan.pl line 993.
Bad arg length for Socket::inet_ntoa, length is 0, should be 4 at atscan.pl line 993.
How i can resolve that for complete scan ? And how i can get more result for dork why when i text on google inurl:".php?cat="intext:"Buy Now" i get 185.000 result and with atscan when i set level 1000 i get just 248 result and stop to work at [72/248] ? Thanks :)

**Comment by AlisamTechnology** [comment]
i sent u an email

**Comment by cacaocaca** [comment]
On my email i look just this answer of github

**Comment by AlisamTechnology** [comment]
ok. use it now download last version. 
remember that bing doesnt support inurl / intext ... arguments i have maken some changes to make it founctioning.

**Comment by cacaocaca** [comment]
Thanks work :)

**Comment by AlisamTechnology** [comment]
ok

**Comment by ManchoD6** [comment]
I NEED HELP 



                    ALISAM  TECHNOLOGY                               [ ]
[ ]                  atscan Tool Install Script                           [ ]
[ ]=======================================================================[ ]
[ ] MIT License                                                           [ ]
[ ] Copyright (c) 2015 Alisam Technology                                  [ ]
[ ]                                                                       [ ]
[ ] Permission is hereby granted, free of charge, to any person obtaining [ ]
[ ] a copy of this software and associated documentation files (atscan),  [ ]
[ ] to dealin the Software without restriction, including without         [ ]
[ ] limitation the rights to use, copy, modify, merge, publish,           [ ]
[ ] distribute, sublicense, and/or sellcopies of the Software, end to     [ ]
[ ] permit persons to whom the Software is furnished to do so, subject    [ ]
[ ] to the following conditions:                                          [ ]
[ ]                                                                       [ ]
[ ] The above copyright notice and this permission notice shall be        [ ]
[ ] included in all copies or substantial portions of the Software.       [ ]
[ ]                                                                       [ ]
[ ] THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS [ ]
[ ] OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF            [ ]
[ ] MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT [ ]
[ ] IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  [ ]
[ ] CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  [ ]
[ ] TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     [ ]
[ ] SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                [ ]
[ ]=======================================================================[ ]

[!] By installing this software you agree to our terms! [Y/n]:
Y

[i] Checking directories...
[!] Where do you want to install ATSCAN?
    Set path or press enter to use default [/usr/share/]:
usr
[!] usr does not exist!
[!] Set path or press enter to use default [/usr/share/]:

[!] Installing.. Plaise wait...
./install.sh: line 103: [: .: unary operator expected
[i] Creating symbolic link...                                      [12%]
[i] Creating Completion link...                                    [18%]
chmod: cannot access '/inc/user/atscan': No such file or directory
cp: cannot stat '/inc/user/atscan': No such file or directory
[i] Setting update files...                                        [30%]
./install.sh: line 123: /inc/user/uplog.log: No such file or directory
./install.sh: line 124: /inc/user/version.log: No such file or directory
[i] Creating shirt links...                                        [38%]
cp: cannot stat '/inc/user/desktop/atscan.desktop': No such file or directory
Warning! Failed to add direct access to the applications menu!
[i] Copying icons...                                               [47%]
cp: cannot stat '/inc/user/desktop/16x16/atscan-menu.png': No such file or directory
cp: cannot stat '/inc/user/desktop/22x22/atscan-menu.png': No such file or directory
cp: cannot stat '/inc/user/desktop/24x24/atscan-menu.png': No such file or directory
cp: cannot stat '/inc/user/desktop/48x48/atscan-menu.png': No such file or directory
cp: cannot stat '/inc/user/desktop/256x256//atscan-menu.png': No such file or directory
[i] Copying README.md to /usr/share/doc/atscan...                  [75%]
chmod: cannot access '/README.md': No such file or directory
cp: cannot stat '/README.md': No such file or directory
[i] Copying License.txt to /usr/share/doc/atscan...                [83%]
chmod: cannot access '/License.txt': No such file or directory
cp: cannot stat '/License.txt': No such file or directory
[i] Removing install files...                                      [92%]
rm: cannot remove '/inc/user/atscan': No such file or directory
rm: cannot remove '/install.sh': No such file or directory
rm: cannot remove '/README.md': No such file or directory
rm: cannot remove '/License.txt': No such file or directory
[!] Installation faid!!



HOW TO SOLVE THIS

**Comment by AlisamTechnology** [comment]
because you have no /usr/share/ folder in your system so you have to give a valid exixting folder path
